name: Build and Deploy Error Pages

on:
  push:
    branches:
      - main  # or the branch you want to trigger on

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 24
        cache: 'npm'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build using Parcel
    - name: Build
      env:
        PARCEL_WORKER_BACKEND: process
      run: npm run build

    # Deploy root directory
    - name: Deploy to Dist Branch
      run: |
        # Configure Git
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Delete the files we want to exclude so they aren't indexed
        rm -rf node_modules package-lock.json

        # Create a fresh, empty branch
        git checkout --orphan dist-branch
        
        # Add all remaining files (the new contents)
        git add .
        
        # Commit and Force Push to overwrite the remote 'dist' branch
        git commit -m "Deploy to dist"
        git push origin dist-branch:dist --force